#!/usr/bin/env Rscript
args = commandArgs(trailingOnly=TRUE)
usageMessage=paste0(
    "\t 1 - Input bed file\n",
    "\t 2 - HiRise scaffold composition table (full or filtered)\n",
    "\t 3 - YAGCloser original_coordinates edits file.\n",
    "\t 4 - YAGCloser final edits file. \n",
    "\t 5 - Prefix for output file. Edits only, and not supported HiRise joins breaks.\n",
    "\t     (Tab-separated values (TSV) format)\n",
    "\t     <scaffold_id>     <gap_start>    <gap_end>   <sequence>)"
)
if(length(args)!=5){
    stop(paste0("ERROR: 5 arguments must be supplied.\n", usageMessage), call.=FALSE)
}


bedfile=args[1]
hirise_joins=args[2]
yagcloser_original_coordinates_filename=args[3]
yagcloser_edits_filename=args[4]
output_prefix=args[5]

if(!file.exists(bedfile)){ 
    stop(paste0(
        "ERROR: File ",
        bedfile,
        " does not exist. Please verity.\n", usageMessage), call.=FALSE)
}
if(!file.exists(hirise_joins)){ 
    stop(paste0(
        "ERROR: File ",
        hirise_joins,
        " does not exist. Please verity.\n", usageMessage), call.=FALSE)
}
if(!file.exists(yagcloser_original_coordinates_filename)){ 
    stop(paste0(
        "ERROR: File ",
        yagcloser_original_coordinates_filename,
        " does not exist. Please verity.\n", usageMessage), call.=FALSE)
}
if(!file.exists(yagcloser_edits_filename)){ 
    stop(paste0(
        "ERROR: File ",
        yagcloser_edits_filename,
        " does not exist. Please verity.\n", usageMessage), call.=FALSE)
}


# detet_hirise_joins_with_no_support.R

data=read.table(
    hirise_joins,
    stringsAsFactors=F,
    header=F)
data=data[,c(1,6,7)]
colnames(data)=c("scaffold", "start","end")
data2=sapply(split(data, data$scaffold), function(c){
    coordinates=sort(c(c$start,c$end));
    coordinates=coordinates[2:(length(coordinates)-1)];
    matrix(coordinates,nrow=(length(coordinates)/2),byrow=T)
})

final=c()
for (n in names(data2)){
    d=data.frame(data2[n][[1]])
    d=cbind(rep(n, nrow(d)), d)
    colnames(d)=c("scaffold","start","end")
    final=rbind(
        final,
        d
    )
}
final$code=paste0(final$scaffold,":",final$start,"-",final$end)
# Final are the gaps generated by HiRIse
# Gaps after hirise
# Read all gaps, assign IDs, assign IDs to final
gaps=read.table(bedfile, stringsAsFactors=F, header=F)
colnames(gaps)=c("scaffold", "start","end")
gaps$id=0
x=sapply(split(gaps,gaps$scaffold), function(xx){0:(nrow(xx)-1)})
for(sc in unique(gaps$scaffold)){
    gaps[gaps$scaffold==sc,]$id = x[sc][[1]]
}
gaps$code=paste0(gaps$scaffold,":",gaps$start,"-",gaps$end)

# Gaps closed by YAGCloser
closed=read.table(yagcloser_original_coordinates_filename,
    stringsAsFactors=F,header=F)
colnames(closed)=c("scaffold", "start","end")
closed$code=paste0(closed$scaffold,":",closed$start,"-",closed$end)

# assignigs codes to intercept IDs between FINAL and GAPS
# missing information on the closed gaps by HiRiSe
hirisejoins=intersect(gaps$code,final$code)
# 2505 HiRise joins - What's on the report minus the gap closed by merauder
hiriseclosed=intersect(hirisejoins, closed$code)
hirisenotclosed=setdiff(hirisejoins,hiriseclosed)

final$id=0
for (code in hirisejoins){
    final[final$code==code, ]$id=gaps[gaps$code==code,]$id
}

tobreak=gaps[gaps$code %in% hirisenotclosed,]

edits=read.table(yagcloser_edits_filename, stringsAsFactors=F, header=F, fill=T)
colnames(edits)=c("scaffold","start","end","sequence")
indices=which(closed$code %in% hiriseclosed)
indices2=which(! closed$code %in% hiriseclosed)
lens=as.numeric(lapply(as.character(edits[indices, ]$sequence), nchar))
lens2=as.numeric(lapply(as.character(edits[indices2, ]$sequence), nchar))
closed_gaps_hirise=sum(lens==0)
filled_gaps_hirise=sum(lens!=0)
closed_gaps_nohirise=sum(lens2==0)
filled_gaps_nohirise=sum(lens2!=0)

print(paste("Number of gaps generated by last HiRise run closed:\n",closed_gaps_hirise))
print(paste("Number of gaps generated by last HiRise run filled:\n",filled_gaps_hirise))
print("Summary statistics of the filling sequences generated")
print(summary(lens))
print(paste("Number of gaps not generated by last HiRise run closed:\n",closed_gaps_nohirise))
print(paste("Number of gaps not generated by last HiRise run filled:\n",filled_gaps_nohirise))
print("Summary statistics of the filling sequences generated")
print(summary(lens2))

tobreakedits=tobreak[,1:3]
tobreakedits$sequence="-"
alledits=rbind(edits,tobreakedits)
alledits=alledits[order(alledits$scaffold, alledits$start),]
write.table(alledits,file=paste0(output_prefix, ".edits.and.breaks.txt"), sep="\t",quote=F, row.names=F, col.names=F)
write.table(edits,file=paste0(output_prefix, ".edits.only.txt"), sep="\t",quote=F, row.names=F, col.names=F)