#!/usr/bin/python
import pysam,gzip,  argparse,datetime, collections, csv, os, sys, filetype, logging
import numpy as np
from Bio import SeqIO

# ========================================================================================
PROGRAM_NAME="extract_sequences_from_fasta"
VERSION=2
MIN_VERSION=0
FIX_VERSION=0
# ========================================================================================
APPLOGGER = logging.getLogger(PROGRAM_NAME)
APPLOGGER.setLevel(logging.DEBUG)
ch = logging.StreamHandler()
ch.setLevel(logging.DEBUG)
loggerFormatter = logging.Formatter(\
  fmt = "[%(asctime)s]  %(levelname)s (%(funcName)s|%(lineno)d): %(message)s",\
  datefmt = "%d/%m/%Y %I:%M:%S %p")
ch.setFormatter(loggerFormatter)
APPLOGGER.addHandler(ch)

def run(parameters):
  message="All correct."
  APPLOGGER.info("Reading file...")
  handle=None
  filekind=filetype.guess(parameters['input'])
  if filekind and filekind.extension in ['gz','GZ','gZ','Gz']:
    APPLOGGER.info("Running gzip...")
    handle=gzip.open(parameters['input'], "rt")
  else:
    handle=open(parameters['input'], "rt")
  APPLOGGER.info("Creating output file...")
  APPLOGGER.info("Parsing FASTA file...")
  for record in SeqIO.parse(handle, "fasta"):
    if record.id == parameters['name']:
      with open(parameters['output'], "wb") as outhandle:
        _=SeqIO.write(record,outhandle,"fasta")
      break
  APPLOGGER.info("Closing files...")
  handle.close()
  return 0, message

def main():
  parser = argparse.ArgumentParser(\
  prog=PROGRAM_NAME,\
    description='Extracts sequences from a multiple sequence FASTA file given sequence descriptions/IDs',\
    add_help=True\
  )
  requiredArgs=parser.add_argument_group("{0}required arguments{1}".format("\033[1m","\033[0m"))
  requiredArgs.add_argument(\
    '-i','--input',\
    metavar = '<multiple_sequences.fasta>',\
    type = str,\
    required = True,\
    help = 'Filepath of the reference genome file to be used.')
  requiredArgs.add_argument(\
    '-o','--output',\
    metavar = '<file_path>',\
    type = str,\
    required = True,\
    help = 'Output file path.')
  seqArgs=parser.add_argument_group("{0}sequence selection arguments{1} At least one should be used".format("\033[1m","\033[0m"))
  seqArgs.add_argument(\
    '-n','--name',\
    metavar = '<sequences.name>',\
    type = str,\
    required = True,\
    help = 'Identifier of the sequence to be extrcted.')
  informationGroup= parser.add_argument_group("{0}information arguments{1}".format("\033[1m","\033[0m"))
  informationGroup.add_argument(\
    '-l','--log',\
    metavar = '<log_level>',\
    type = str,\
    choices = ['INFO','DEBUG'],\
    default= 'INFO',\
    help = 'Verbosity levels.')
  informationGroup.add_argument('-v', '--version',\
    action='version',\
    version='{0}: Version {1}.{2}.{3}'.format(PROGRAM_NAME,VERSION,MIN_VERSION,FIX_VERSION),\
    help="Show program's version number and exit")
  try:
    args = parser.parse_args()  
    APPLOGGER.debug(args)
    parameters=dict()
    # Checking files
    if args.log == 'DEBUG':
      APPLOGGER.setLevel(logging.DEBUG)
    else:
      APPLOGGER.setLevel(logging.INFO)
    if (os.path.exists(os.path.abspath(args.input))):
      REFFILE=os.path.abspath(args.input)
    else:
      message="Reference file does not exist. Please verify. Exiting."
      return (-1, message)
    OUTPUT=os.path.abspath(args.output)
    if (os.path.exists(OUTPUT)):
      message="Output file exist. Not overwriting. Please verify. Exiting."
      return (-1, message)
    parameters['output']=OUTPUT
    parameters['input']=REFFILE
    parameters['name']=args.name
    return run(parameters)
  except:
    message="Exiting"
    print("="*80)
    print("Usage and help")
    print("="*80)
    parser.print_help()
    return (-1, message)

if __name__ == "__main__":
  SIGNAL_EXIT,MESSAGE=main()
  if SIGNAL_EXIT == -1:
    APPLOGGER.error(MESSAGE)
  else:
    APPLOGGER.info(MESSAGE)
  sys.exit(SIGNAL_EXIT)
