#!/usr/bin/python
import pysam,gzip, argparse,datetime, collections, csv, os, sys, filetype, logging, copy
import numpy as np
from Bio import SeqIO, Seq, AlignIO
# ========================================================================================
PROGRAM_NAME="fasta_multi_to_single_seq_line"
VERSION=1
MIN_VERSION=0
FIX_VERSION=0
# ========================================================================================
APPLOGGER = logging.getLogger(PROGRAM_NAME)
APPLOGGER.setLevel(logging.DEBUG)
ch = logging.StreamHandler()
ch.setLevel(logging.DEBUG)
loggerFormatter = logging.Formatter(\
  fmt = "[%(asctime)s]  %(levelname)s (%(funcName)s|%(lineno)d): %(message)s",\
  datefmt = "%d/%m/%Y %I:%M:%S %p")
ch.setFormatter(loggerFormatter)
APPLOGGER.addHandler(ch)
#=========================================================================================
def readGenomeAssembly(parameters):
    # read genome assembly file    d=d[which(d$coord1<start),]
    scaffolds=dict()
    APPLOGGER.info("Reading genome file...")
    handle=None
    filekind=filetype.guess(parameters['genome_filename'])
    if filekind and filekind.extension in ['gz','GZ','gZ','Gz']:
        APPLOGGER.info("Running gzip...")
        handle=gzip.open(parameters['genome_filename'], "rt")
    else:
        handle=open(parameters['genome_filename'], "rt")
    scaffolds=SeqIO.to_dict(SeqIO.parse(handle, "fasta")) 
    handle.close()
    return scaffolds

#=========================================================================================

def run(parameters):
    try:
        APPLOGGER.info("Starting...")
        scaffolds=readGenomeAssembly(parameters)
        # Generating scaffolds/contigs  with no modifications
        with open(parameters['output_filename_full'], 'wb') as handle:
            for index in sorted(scaffolds):
                handle.write("{}\n{}\n".format(\
                    index,\
                    str(scaffolds[index].seq).replace('\n', '')))
    except Exception as ex:
        return -1, ex.message
    return 0,"Done."


def main():
    parser = argparse.ArgumentParser(\
    prog=PROGRAM_NAME,\
        description='Transforms a multi-line sequence FASTA file to a '+\
            'single-line seqeunce FASTA',\
        add_help=True\
    )
    requiredArgs=parser.add_argument_group("{0}Required arguments{1}".format("\033[1m","\033[0m"))
    requiredArgs.add_argument(\
        '-i','--input',\
        metavar = '<sequences.fasta>',\
        type = str,\
        required = True,\
        help = 'Filepath of the FASTA file to be used (accepts .gz.)')
    requiredArgs.add_argument(\
        '-o','--output',\
        metavar = '<file_path>',\
        type = str,\
        required = True,\
        help = 'Output file path.')        
    optionalArts=parser.add_argument_group("{0}Optional arguments{1}".format("\033[1m","\033[0m"))
    optionalArts.add_argument(\
        '-l','--log',\
        metavar = '<log_level>',\
        type = str,\
        choices = ['INFO','DEBUG'],\
        default= 'INFO',\
        help = 'Verbosity levels.')
    informationGroup= parser.add_argument_group("{0}Information arguments{1}".format("\033[1m","\033[0m"))
    informationGroup.add_argument('-v', '--version',\
        action='version',\
        version='{0}: Version {1}.{2}.{3}'.format(PROGRAM_NAME,VERSION,MIN_VERSION,FIX_VERSION),\
        help="Show program's version number and exit")
    try:
        args=parser.parse_args()
        parameters=dict()
        # Checking files
        if args.log == 'DEBUG':
            APPLOGGER.setLevel(logging.DEBUG)
        else:
            APPLOGGER.setLevel(logging.INFO)
        APPLOGGER.debug(args)
        # Checking input file
        if (os.path.exists(os.path.abspath(args.input))):
            REFFILE=os.path.abspath(args.input)
        else:
            message="Reference file does not exist. Please verify. Exiting."
            return (-1, message)
        # Checkiong output file
        if not (os.path.exists(os.path.abspath(args.output))):
            OUTPUT=os.path.abspath(args.output)
        else:
            message="Output file exist. File will NOT be overwritten. Please verify. Exiting."
            return (-1, message)
        parameters['genome_filename']=REFFILE
        parameters['output_filename_full']=OUTPUT
        filename, file_extension = os.path.splitext(OUTPUT)
        return run(parameters)
    except:
        message="Parsing error. Exiting"
        return (-1, message)


if __name__ == "__main__":
    SIGNAL_EXIT,MESSAGE=main()
    if SIGNAL_EXIT == -1:
        APPLOGGER.error(MESSAGE)
    else:
        APPLOGGER.info(MESSAGE)
    sys.exit(SIGNAL_EXIT)

# APPLOGGER.info("Starting...")
# scaffolds=readGenomeAssembly(parameters)
# edits=readEditsFile(parameters,scaffolds)
# newscaffolds=[]
# contigs=[]
# newoutput=parameters['output_full']
# newoutput2=parameters['output_contigs']


# assemblyfile="/scratch1/merly/Mende/HG03486.assembly.3.fasta"
# editsfile="/scratch1/merly/Mende/gapfilling/mende.3.full.edits.txt"
# newoutput="/scratch1/merly/Mende/HG03486.assembly.4.fasta"
# newoutput2="/scratch1/merly/Mende/HG03486.assembly.5.fasta"



